### ISSUE TITLE
[Question] Recommended way to return a config validation error

### ISSUE THREAD

**Issue by cpmoore** [logstash-plugins/logstash-input-java_input_example#5]
I know you're supposed to validate the configuration in the plugin constructor, but I was wondering if there was a recommended way to return an error.
Currently I'm just logging the error and setting a flag to not start the plugin.  Is there a specific exception I should be throwing?

**Comment by danhermann** [comment]
Typically, an `IllegalStateException` is thrown so Logstash is prevented from starting with an input in an invalid state. You can see an example of that in the `stdin` Java input that is included in Logstash:

https://github.com/elastic/logstash/blob/2360d0f72adb2962e56485cd22222074155c564a/logstash-core/src/main/java/org/logstash/plugins/inputs/Stdin.java#L65
